kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bookstore-covers-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: hcloud-volumes